services:
  # python:
  #   build:
  #     context: ./backend/src/ai
  #     dockerfile: Dockerfile
  #   env_file:
  #     - ./backend/src/ai/.env.prod
  #   restart: unless-stopped
  #   networks:
  #     - app-network

  node:
    build:
      context: ./backend
      dockerfile: Dockerfile
    env_file:
      - ./backend/.env.prod
    restart: unless-stopped
    # depends_on:
    #   - python
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    env_file:
      - ./frontend/.env
    restart: unless-stopped
    depends_on:
      node:
        condition: service_started
    ports:
      - "5173:80"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
